trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMaster: $[eq(variables['Build.SourceBranchName'], 'master')]

stages:
- stage: BuildDockerImageProd
  condition: eq(variables.isMaster, true)
  displayName: Build DOcker image from master
  jobs:
    - job: Approval
      pool: server
      timeoutInMinutes: 4320
      steps:
        - task: ManualValidation@0
          inputs:
            notifyUsers: 'pramanikdipayan007@gmail.com'
            instructions: 'Build image and publish to Dockerhub'
    - job: BuildImage
      dependsOn: Approval
      displayName: Build Docker image
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'mydockerhub'
          repository: 'dipayanp007/botkube-teams-proxy'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'

- stage: BuildDockerImageTest
  condition: eq(variables.isMaster, false)
  dependsOn: []
  displayName: Build DOcker image from master
  jobs:
    - job: BuildImage
      displayName: Build Docker image
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'mydockerhub'
          repository: 'dipayanp007/botkube-teams-proxy-test'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'