apiVersion: v1
kind: Service
metadata:
  name: botkube-teams-proxy
spec:
  type: ClusterIP
  selector:
    app: botkube-teams-proxy
  ports:
    - port: 80
      targetPort: 4000
      name: proxyport